# Generated by Django 4.2.21 on 2025-06-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_product_price_variation"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="allowed_variations",
            field=models.CharField(
                blank=True,
                help_text="Comma separated list of allowed variation types (e.g. color,size)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="variation",
            name="variation_category",
            field=models.CharField(
                choices=[("color", "color"), ("size", "size"), ("pack", "pack")],
                max_length=100,
            ),
        ),
    ]
