# Generated by Django 4.2.21 on 2025-07-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_productgallery_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='allowed_variations',
            field=models.CharField(blank=True, help_text='Comma separated list of allowed variation types (e.g. color,size,pack)', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Product description. If this is a plant product, include the plant name to automatically display care information.', max_length=500),
        ),
    ]
