# Generated by Django 4.2.21 on 2025-07-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_allowed_variations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
