# Generated by Django 4.2.21 on 2025-06-15 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0003_rename_date_added_cart_date_added_cartitem_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="variations",
            new_name="variation",
        ),
    ]
