"""
Django settings for plantae project.

Generated by 'django-admin startproject' using Django 4.2.21.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config
from dotenv import load_dotenv
from django.contrib.messages import constants as messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = ['www.plantaeai.tech', 'plantaeai.tech', '20.193.248.79']
if DEBUG:
    ALLOWED_HOSTS += ['localhost', '127.0.0.1']
# Extra hosts, e.g. a temporary tunnel used to receive Slack webhooks in development.
EXTRA_ALLOWED_HOSTS = [h.strip() for h in os.getenv('EXTRA_ALLOWED_HOSTS', '').split(',') if h.strip()]
ALLOWED_HOSTS += EXTRA_ALLOWED_HOSTS

CSRF_TRUSTED_ORIGINS = [
    'https://plantaeai.tech',
    'https://www.plantaeai.tech',
]
CSRF_TRUSTED_ORIGINS += [f'https://{h}' for h in EXTRA_ALLOWED_HOSTS]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "category",
    "accounts",
    "store",
    "carts",
    "orders",
    "agent",
    "django_q",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "plantae.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "category.context_processors.menu_links",
                "carts.context_processors.counter",
                "agent.context_processors.chat_widget",
                "accounts.context_processors.user_context"
            ],
        },
    },
]

WSGI_APPLICATION = "plantae.wsgi.application"

AUTH_USER_MODEL = 'accounts.Account'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST'),
        'PORT': os.environ.get('DB_PORT', '5432'),
        'OPTIONS': {
            'sslmode': os.environ.get('DB_SSLMODE', 'require'),
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_ROOT = BASE_DIR / 'static'
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'plantae' / 'static',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR /'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

MESSAGE_TAGS = {
    messages.ERROR:'danger',
}

# SMTP config
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = os.environ.get('EMAIL_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_PASS')
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

RAZORPAY_KEY_ID = os.getenv('RAZORPAY_KEY_ID')
RAZORPAY_KEY_SECRET = os.getenv('RAZORPAY_KEY_SECRET')

# --- Human-in-the-loop (agent escalations) ---
# Slack is optional: when SLACK_BOT_TOKEN is unset, tickets are handled from the
# Django admin and staff are notified by email only.
SLACK_BOT_TOKEN = os.getenv('SLACK_BOT_TOKEN', '')
SLACK_SIGNING_SECRET = os.getenv('SLACK_SIGNING_SECRET', '')
SLACK_ESCALATION_CHANNEL = os.getenv('SLACK_ESCALATION_CHANNEL', '')
HITL_STAFF_EMAILS = [e.strip() for e in os.getenv('HITL_STAFF_EMAILS', '').split(',') if e.strip()]
HITL_SLA_MINUTES = int(os.getenv('HITL_SLA_MINUTES', '30'))
HITL_EXPIRE_HOURS = int(os.getenv('HITL_EXPIRE_HOURS', '24'))
# Bump (or set via env on deploy) whenever the chat widget's CSS/JS change, so
# browsers fetch the new files instead of mixing cached old ones with new markup.
CHAT_WIDGET_VERSION = os.getenv('CHAT_WIDGET_VERSION', '2026.10.08.1')
# Approved price matches become a user-specific coupon for the product.
PRICE_MATCH_MAX_UNITS = int(os.getenv('PRICE_MATCH_MAX_UNITS', '2'))
PRICE_MATCH_VALID_DAYS = int(os.getenv('PRICE_MATCH_VALID_DAYS', '7'))
# Base URL used to link to tickets from Slack/email.
SITE_URL = os.getenv('SITE_URL', 'https://plantaeai.tech')

# Background worker (python manage.py qcluster). Uses the existing Postgres DB
# as the queue so no Redis is required.
Q_CLUSTER = {
    'name': 'plantae',
    'orm': 'default',
    'workers': int(os.getenv('Q_WORKERS', '2')),
    'timeout': 120,
    'retry': 180,
    'max_attempts': 2,
    'catch_up': False,
}

# Logging — agent failures are also persisted to the AgentError model (see
# agent/error_logging.py) and surfaced in the admin panel.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'agent.errors': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'agent.hitl': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}