# Generated by Django 4.2.21 on 2025-06-18 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="pin_code",
            field=models.CharField(
                default=829149,
                max_length=6,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_pin",
                        message="Pin code must be exactly 6 digits",
                        regex="^\\d{6}$",
                    )
                ],
            ),
            preserve_default=False,
        ),
    ]
