# Generated by Django 4.2.21 on 2025-07-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_pin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='chat_limit_reset',
            field=models.BooleanField(default=False, help_text='Tick to allow admin to reset chat rate limit for this user.'),
        ),
    ]
