# Generated by Django 4.2.21 on 2025-07-08 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_chat_limit_reset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='chat_limit_reset',
        ),
    ]
