# Generated by Django 4.2.21 on 2025-07-07 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
            ],
            options={
                'verbose_name': 'Chat Session',
                'verbose_name_plural': 'Chat Sessions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('agent.chatmessage',),
        ),
    ]
