# Generated by Django 4.2.21 on 2025-07-08 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_chatsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='session_id',
        ),
    ]
