# Generated by Django 4.2.21 on 2026-09-02 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agent', '0004_chatimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=100)),
                ('user_message', models.TextField(blank=True)),
                ('error_message', models.TextField()),
                ('traceback', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Error',
                'verbose_name_plural': 'Agent Errors',
                'ordering': ('-created_at',),
            },
        ),
    ]
