# Generated by Django 4.2.21 on 2026-10-07 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agent', '0005_agenterror'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalationTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('price_match', 'Price match / better deal'), ('bulk_order', 'Bulk or custom order'), ('cancellation', 'Order cancellation'), ('damaged_item', 'Damaged / wrong item'), ('payment_issue', 'Payment issue'), ('delivery', 'Delivery issue'), ('human_request', 'Asked for a human'), ('complaint', 'Complaint'), ('other', 'Other')], default='other', max_length=20)),
                ('mode', models.CharField(choices=[('assist', 'Staff approve AI proposal'), ('takeover', 'Staff chat with user')], default='assist', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('awaiting_staff', 'Awaiting staff'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_takeover', 'In takeover'), ('resolved', 'Resolved'), ('expired', 'Expired')], db_index=True, default='open', max_length=20)),
                ('trigger', models.CharField(blank=True, max_length=50)),
                ('summary', models.TextField(blank=True)),
                ('collected_info', models.JSONField(blank=True, default=dict)),
                ('proposed_action', models.JSONField(blank=True, default=dict)),
                ('final_action', models.JSONField(blank=True, null=True)),
                ('staff_note', models.TextField(blank=True)),
                ('graph_thread_id', models.CharField(blank=True, max_length=64)),
                ('slack_channel', models.CharField(blank=True, max_length=64)),
                ('slack_ts', models.CharField(blank=True, db_index=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('sla_reminded_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Escalation Ticket',
                'verbose_name_plural': 'Escalation Tickets',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TicketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ai', 'AI'), ('slack', 'Slack'), ('admin', 'Admin'), ('system', 'System'), ('user', 'User')], max_length=10)),
                ('kind', models.CharField(max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='agent.escalationticket')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='agent.escalationticket'),
        ),
    ]
