# Generated by Django 4.2.21 on 2025-06-14 07:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="pin_code",
            field=models.IntegerField(
                default=829149,
                validators=[
                    django.core.validators.MinValueValidator(100000),
                    django.core.validators.MaxValueValidator(999999),
                ],
            ),
            preserve_default=False,
        ),
    ]
