# Generated by Django 4.2.21 on 2025-06-14 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_pin_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_phone",
                        message="Phone number must be exactly 10 digits",
                        regex="^\\d{10}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="pin_code",
            field=models.CharField(
                max_length=6,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_pin",
                        message="Pin code must be exactly 6 digits",
                        regex="^\\d{6}$",
                    )
                ],
            ),
        ),
    ]
