# Generated by Django 4.2.21 on 2025-06-15 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_razorpay_order_id_alter_order_phone_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderproduct",
            name="color",
        ),
        migrations.RemoveField(
            model_name="orderproduct",
            name="size",
        ),
    ]
