# Generated by Django 4.2.21 on 2025-06-15 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_remove_orderproduct_variation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderproduct",
            name="color",
        ),
        migrations.RemoveField(
            model_name="orderproduct",
            name="size",
        ),
    ]
