# Generated by Django 4.2.21 on 2025-06-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_product_allowed_variations_and_more"),
        ("orders", "0004_remove_orderproduct_color_remove_orderproduct_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderproduct",
            name="variation",
        ),
        migrations.AddField(
            model_name="orderproduct",
            name="variation",
            field=models.ManyToManyField(blank=True, to="store.variation"),
        ),
    ]
