# Generated by Django 4.2.21 on 2025-06-15 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_product_allowed_variations_and_more"),
        ("orders", "0005_remove_orderproduct_color_remove_orderproduct_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderproduct",
            name="variations",
        ),
        migrations.AddField(
            model_name="orderproduct",
            name="variation",
            field=models.ForeignKey(
                default="abc",
                on_delete=django.db.models.deletion.CASCADE,
                to="store.variation",
            ),
        ),
    ]
