# Generated by Django 4.2.21 on 2025-06-15 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_product_allowed_variations_and_more"),
        ("orders", "0006_remove_orderproduct_variations_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproduct",
            name="variation",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.variation",
            ),
        ),
    ]
